[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[context.production.environment]
  VITE_SUPABASE_ANON_KEY = "YOUR_ANON_KEY"
  VITE_SUPABASE_URL = "YOUR_SUPABASE_URL"
