name: Verify and Typecheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Remove or comment out the install step:
      # - name: Install dependencies
      #   run: npm install

      # Remove or comment out the typecheck step:
      # - name: Type check
      #   run: npm run typecheck
